In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from pycaret.classification import *

In [2]:
df = pd.read_csv("data01.csv")

In [10]:
X = df.drop(["outcome"], axis=1)
y = df["outcome"]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4242)

In [14]:
df = df.dropna(how="any")

In [15]:
model = setup(data=df, target="outcome")

In [16]:
compare_models()

RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=5341, solver='auto',
                tol=0.0001)

In [17]:
ridge_model = create_model("ridge")

In [18]:
y_pred = predict_model(ridge_model, data=X_test)

In [19]:
y_pred

,group,ID,age,gendera,BMI,hypertensive,atrialfibrillation,CHD with no MI,diabetes,deficiencyanemias,...,Blood calcium,Chloride,Anion gap,Magnesium ion,PH,Bicarbonate,Lactic acid,PCO2,EF,prediction_label
1016,2,145248,77,1,27.261074,1,0,0,1,0,...,8.787500,108.750000,17.750000,1.900000,7.370000,19.875000,2.050000,28.000000,75,0
174,1,119090,46,2,17.093426,0,0,0,0,1,...,9.314285,100.375000,13.875000,1.911111,7.460000,24.000000,1.200000,34.000000,55,0
901,2,190269,54,2,25.515089,1,1,0,1,0,...,8.187500,105.777779,11.888889,2.225000,7.340909,29.111111,1.300000,49.299999,55,0
1060,2,125483,81,2,24.369493,1,0,0,0,1,...,9.425000,105.428574,18.285715,2.015385,7.423333,19.928572,2.666667,29.333334,35,0
595,1,178127,62,1,31.869389,0,1,1,1,0,...,8.075000,102.777779,13.111111,1.912500,7.406667,25.666666,2.850000,43.000000,30,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
650,1,184331,92,1,18.771664,1,1,1,0,0,...,8.333333,106.666664,16.666666,1.966667,7.326667,21.333334,4.300000,33.666668,35,1
829,2,140961,65,2,41.363964,1,0,0,1,0,...,9.500000,101.666664,14.000000,2.057143,7.320000,29.125000,0.733333,46.000000,55,0
114,1,158130,51,1,69.965416,1,0,0,1,1,...,8.577778,99.599998,11.900000,2.208333,7.443182,34.000000,1.100000,54.545456,55,0
46,1,130036,64,2,36.537704,0,0,0,1,0,...,8.900000,97.800003,9.800000,2.000000,7.350833,32.400002,0.860000,62.500000,55,0
834,2,133934,85,2,43.064602,1,0,0,1,1,...,8.750000,104.666664,8.666667,2.000000,7.340000,34.333332,0.800000,62.500000,55,0